"""empty message

Revision ID: a2f4327be73d
Revises: d01e5b90bcca
Create Date: 2017-04-08 13:51:38.753777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2f4327be73d'
down_revision = 'd01e5b90bcca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_profile', sa.Column('userid', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'item_profile', 'user_profile', ['userid'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'item_profile', type_='foreignkey')
    op.drop_column('item_profile', 'userid')
    # ### end Alembic commands ###
