"""empty message

Revision ID: a37fc66ae61e
Revises: 39243fbf5f3d
Create Date: 2017-04-26 20:26:17.340560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a37fc66ae61e'
down_revision = '39243fbf5f3d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userid', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=140), nullable=True),
    sa.Column('description', sa.String(length=2048), nullable=True),
    sa.Column('url', sa.String(length=512), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['userid'], ['user_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item_profile')
    # ### end Alembic commands ###
